name: Build Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/**'

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install mkdocs
        run: pip install mkdocs-material

      - name: Build with mkdocs
        run: cd website && mkdocs build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: website/site/
          fqdn: grafana-weathermap.seth.cx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
